name: Deploy Docker Application to EKS with ELK

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build and Push Docker Image to ECR
        id: docker_build
        run: |
          COMMIT_ID=$(git rev-parse --short=7 ${{ github.sha }})
          # Tagging the Docker image for ECR
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/pocrepo:$COMMIT_ID --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} .
          # Logging into ECR
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
          # Pushing the Docker image to ECR
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/pocrepo:$COMMIT_ID
          echo "::set-output name=commit_id::$COMMIT_ID"
          docker images

      - name: Update deployment.yml
        run: |
          sed -i "s|image:.*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/pocrepo:${{ steps.docker_build.outputs.commit_id }}|" deployment.yaml

      - name: Update Kubeconfig
        run: aws eks --region us-east-2 update-kubeconfig --name sanjay_poc  # Replace with your EKS cluster name

          # - name: Deploy ELK using Helm
        #run: |
          #helm repo add elastic https://helm.elastic.co
          #helm repo update
          #helm upgrade --install elasticsearch values-Kibana.yaml --namespace elastic-stack2
          #helm upgrade --install kibana values-Elastic.yaml --namespace elastic-stack2
          #kubectl apply -f values-Logstash.yaml  # Replace with your Logstash deployment file

      - name: Deploy to EKS
        run: kubectl apply -f deployment.yaml

